version: '3.3'
services:
    keystone:
        build:
            context: ..
            dockerfile: ./docker/keystone.prod.dockerfile
        command: yarn deploy
        environment:
            DATABASE_URL: ${DATABASE_URL}
            SESSION_SECRET: ${SESSION_SECRET}
