version: '3.3'
services:
    keystone:
        environment:
            PORT: ${KEYSTONE_PORT}
        volumes:
            - keystone_node_modules:/app/node_modules
        ports:
            - ${KEYSTONE_PORT}:${KEYSTONE_PORT}
volumes:
    keystone_node_modules:
